### ISSUE TITLE
Got an issue french phrase

### ISSUE THREAD

**Issue by amarCosmospace** [Donatello-za/rake-php-plus#12]
This phrase give me this keywords. But i want to have the "top 14" in the same keyword. How can i achieve that ?
 
"Rugby - Top 14 : Direction les États-Unis pour Mathieu Bastareaud ?"
```
$text = "Rugby - Top 14 : Direction les États-Unis pour Mathieu Bastareaud ?";
$phrases = RakePlus::create($text, 'fr_FR', 2, false)->get();
$rake = RakePlus::create($text, 'fr_FR', 2, false);
$keywords = $rake->keywords();

var_dump($phrases,$keywords);
```
```
array(8) {
  [0]=>
  string(5) "rugby"
  [1]=>
  string(3) "top"
  [2]=>
  int(14)
  [3]=>
  string(9) "direction"
  [4]=>
  string(4) "unis"
  [5]=>
  string(4) "pour"
  [6]=>
  string(7) "mathieu"
  [7]=>
  string(10) "bastareaud"
}
array(8) {
  [0]=>
  string(5) "rugby"
  [1]=>
  string(3) "top"
  [2]=>
  string(2) "14"
  [3]=>
  string(9) "direction"
  [4]=>
  string(4) "unis"
  [5]=>
  string(4) "pour"
  [6]=>
  string(7) "mathieu"
  [7]=>
  string(10) "bastareaud"
}
```

**Comment by Donatello-za** [comment]
Hi, thanks for posting the issue. I'll take a look at the problem and see if any improvements can be made. Just as a side note, you are probably going to run into other issues too if there is a mix of different languages in the same text.

**Comment by amarCosmospace** [comment]
Thanks, yes for now our main language is english. We will see how to handle it.

Cordialement,
L'équipe Point Mp3

**Comment by Donatello-za** [comment]
To add to my previous comment. This seems to be a bug as the phrases are not extracted correctly, I think it might have something to do with the dash/minus characters within the French language pattern file which might be throwing out the regular expression that the extractor uses. I've marked this as a bug and will try and fix it ASAP.

**Comment by amarCosmospace** [comment]
Ok thanks :)

**Comment by Donatello-za** [comment]
Hi, I've just released a new version: v1.0.10 but you may want to wait for [packagist.org](https://packagist.org/packages/donatello-za/rake-php-plus) to pick up the new version first, it takes a few hours sometimes.

With this release the sentence you provided: `Rugby - Top 14 : Direction les États-Unis pour Mathieu Bastareaud ?` will be extracted into the following keywords:
```
Array
(
    [0] => rugby
    [1] => -
    [2] => top
    [3] => 14
    [4] => direction
    [5] => états-unis
    [6] => mathieu
    [7] => bastareaud
)
```

and the following phrases:

```
Array
(
    [0] => rugby - top 14
    [1] => direction
    [2] => états-unis
    [3] => mathieu bastareaud
)
```

I've made some other small improvements too. I'm thinking of putting some way of optionally "cleaning" up the results in order to remove keywords like " - " within the results. For now you will have to perform your own cleanup.

**Comment by amarCosmospace** [comment]
Hi, waiting for the composer update to test. Thanks for your reactivity

**Comment by amarCosmospace** [comment]
Got the same result on the keywords method. You can see the php code used above, in the first comment

```
array(4) {
  [0]=>
  string(14) "rugby - top 14"
  [1]=>
  string(9) "direction"
  [2]=>
  string(11) "états-unis"
  [3]=>
  string(18) "mathieu bastareaud"
}
array(8) {
  [0]=>
  string(5) "rugby"
  [1]=>
  string(1) "-"
  [2]=>
  string(3) "top"
  [3]=>
  string(2) "14"
  [4]=>
  string(9) "direction"
  [5]=>
  string(11) "états-unis"
  [6]=>
  string(7) "mathieu"
  [7]=>
  string(10) "bastareaud"
}
```

**Comment by amarCosmospace** [comment]
But the wanted result is something more like that for the keywords : 

```
array(8) {
  [0]=>
  string(5) "rugby"
  [1]=>
  string(3) "top 14"
  [2]=>
  string(9) "direction"
  [3]=>
  string(11) "états-unis"
  [4]=>
  string(7) "mathieu"
  [5]=>
  string(10) "bastareaud"
}
```

**Comment by Donatello-za** [comment]
Keywords are single words and phrases may contain multiple words and unfortunately that is not going to be changed. 

You may have to do your own pre-processing on the original sentence or post processing on the phrases to get the results you are looking for. The library is limited in scope since there is an infinite amount of ways people would want to break up or combine sentences. For example, you may have the following cases:

Rugby (top 14)
Rugby, top 14
Rugby "top 14"
Rugby `top-14`

and a more complex example:

"The following scores were made, England 481-6 (50 overs) and Australia 239 (37 overs)"

So as you can see it is nearly impossible for the library to guess what the end results is suppose to be and it is therefore limited to the scope of the original RAKE scientific paper.
