### ISSUE TITLE
Stop words for spanish

### ISSUE THREAD

**Issue by tematres** [Donatello-za/rake-php-plus#8]
Here stop words files for

[lang_es.zip](https://github.com/Donatello-za/rake-php-plus/files/2005661/lang_es.zip)

 spanish

**Comment by Donatello-za** [comment]
I added the Spanish stopword files in v.1.0.8, thank you very much. I had to remove some of the additional stopwords that you had, e.g. numbers 0 to 9 and the '_' character in order to be consistent with the other language files. This shouldn't be a problem as it is easy to strip away keywords that contains only numbers using the `$filter_numerics` boolean option when creating an instance of RakePlus, please see the examples in the README.md file.
